apiVersion: compute.cloud.com/v1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: operator-repo
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-glacier
spec:
  bucketName: my-archive-bucket-example
  region: us-west-2
  acl: private
  storageClass: GLACIER
  versioning: Suspended
